package persistence.sql.dml;

import persistence.sql.metadata.Column;
import persistence.sql.metadata.EntityMetadata;

import java.util.List;

public class DmlQueryBuilder {

    private static final String JOIN_DELIMITER = ", ";

    public <T> String buildInsertQuery(EntityMetadata<T> metadata, T entity) {
        return """
                insert into %s (%s)\s
                values (%s)
                ;"""
                .formatted(
                        metadata.getTableName(),
                        String.join(JOIN_DELIMITER, getColumnNames(metadata.getColumnsWithoutAutoGenerated())),
                        String.join(JOIN_DELIMITER, getColumnValues(metadata.getColumnsWithoutAutoGenerated(), entity))
                );
    }

    private <T> List<String> getColumnNames(List<Column<T>> columns) {
        return columns.stream()
                .map(Column::getName)
                .toList();
    }

    private <T> List<String> getColumnValues(List<Column<T>> columns, T entity) {
        return columns.stream()
                .map(column -> column.extractColumnValue(entity))
                .map(Object::toString)
                .toList();
    }

    public <T> String buildSelectAllQuery(Class<T> entityClass) {
        EntityMetadata<T> metadata = EntityMetadata.from(entityClass);

        return """
                select %s\s
                from %s
                ;"""
                .formatted(
                        String.join(JOIN_DELIMITER, getColumnNames(metadata.getColumns())),
                        metadata.getTableName()
                );
    }

    public <T> String buildSelectByIdQuery(EntityMetadata<T> metadata, Object id) {
        return """
                select %s\s
                from %s\s
                where %s = %s
                ;"""
                .formatted(
                        String.join(JOIN_DELIMITER, getColumnNames(metadata.getColumns())),
                        metadata.getTableName(),
                        metadata.getPrimaryKey().getName(),
                        id
                );
    }

    public <T> String buildDeleteQuery(EntityMetadata<T> metadata, T entity) {
        return """
                delete\s
                from %s\s
                where %s = %s
                ;"""
                .formatted(
                        metadata.getTableName(),
                        metadata.getPrimaryKey().getName(),
                        metadata.extractIdValue(entity)
                );
    }

    public <T> String buildUpdateQuery(EntityMetadata<T> metadata, T entity) {
        return """
                update %s\s
                set %s\s
                where %s
                ;"""
                .formatted(
                        metadata.getTableName(),
                        String.join(JOIN_DELIMITER, equalityExpressions(metadata.getColumnsWithoutAutoGenerated(), entity)),
                        equalityExpression(metadata.getPrimaryKey(), entity)
                );
    }

    private <T> List<String> equalityExpressions(List<Column<T>> columns, T entity) {
        return columns.stream()
                .map(column -> equalityExpression(column, entity))
                .toList();
    }

    private <T> String equalityExpression(Column<T> column, T entity) {
        return column.getName() + " = " + column.extractColumnValue(entity);
    }
}
