package persistence.sql.metadata;

import java.sql.ResultSet;
import java.util.List;

public class EntityMetadata<T> {

    private final Class<T> entityClass;
    private final TableName tableName;
    private final ColumnMetadata<T> columnMetadata;

    private EntityMetadata(Class<T> entityClass, TableName tableName, ColumnMetadata<T> columnMetadata) {
        this.entityClass = entityClass;
        this.tableName = tableName;
        this.columnMetadata = columnMetadata;
    }

    public static <T> EntityMetadata<T> from(Class<T> clazz) {
        return new EntityMetadata<>(clazz, TableName.from(clazz), ColumnMetadata.from(clazz));
    }

    public String getTableName() {
        return tableName.value();
    }

    public String getPrimaryKeyName() {
        return columnMetadata.getPrimaryKey().getName();
    }

    public List<Column<T>> getColumns() {
        return columnMetadata.getColumns();
    }

    public List<Column<T>> getColumnsWithoutAutoGenerated() {
        return columnMetadata.getColumnsWithoutPrimaryKey();
    }

    public void fillId(T entity, long generatedKey) {
        columnMetadata.fillId(entity, generatedKey);
    }

    public ColumnValue extractIdValue(T entity) {
        return columnMetadata.extractIdValue(entity);
    }

    public Column<T> getPrimaryKey() {
        return columnMetadata.getPrimaryKey();
    }

    public void fillEntity(T entity, ResultSet resultSet) {
        columnMetadata.fillEntity(entity, resultSet);
    }

    public Class<T> getEntityClass() {
        return entityClass;
    }
}
